name: Deploy Laravel with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy with Docker
        run: |
          cd /var/www/ulangin
          docker compose pull
          docker compose up -d --build

      - name: Run migrations
        run: |
          cd /var/www/ulangin
          docker compose exec -T laravel php artisan migrate --force
