name: Deploy Laravel with Docker (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Set up Node & build assets
        run: |
          npm ci
          npm run build

      - name: Deploy with Docker Compose
        run: |
          docker compose down
          docker compose up -d --build

      - name: Run Laravel optimizations inside container
        run: |
          docker compose exec -T app php artisan migrate --force
          docker compose exec -T app php artisan config:clear
          docker compose exec -T app php artisan cache:clear
          docker compose exec -T app php artisan route:clear
          docker compose exec -T app php artisan view:clear
          docker compose exec -T app php artisan config:cache
          docker compose exec -T app php artisan route:cache
          docker compose exec -T app php artisan view:cache
